### ISSUE TITLE
Errors at /admin/config/search/path/patterns

### ISSUE THREAD

**Issue by bd0bd** [backdrop-contrib/privatemsg#8] opened 2016-08-10 15:01 UTC
![ddd](https://cloud.githubusercontent.com/assets/13515302/17558795/7e407664-5f24-11e6-839f-aa916d968d4c.png)

**Comment by Graham-72** [comment] 2016-08-10 20:42
@bd0bd it seems that something in privatemsg.module is interfering with tokens. I have narrowed one issue down to the class PrivatemsgMessageController in that module which extends DefaultEntityController. I am a complete novice with programming relating to entities so it may take me a while to identify the cause of the problem, and issue #6 .

**Comment by Radcliffe** [comment] 2019-04-24 20:12
Fixed by PR#12. See issue #9.

**Closed as completed by Radcliffe** 2019-04-24 20:12 UTC
